import type { Metadata } from "next";
import { ThemeProvider } from "./providers";
import NextTopLoader from "nextjs-toploader";
import Nav from "@/components/nav";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader />
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
